# Solving Systems of Linear Equations with NumPy - Lab

## Introduction 

Now you've gathered all the required skills needed to solve systems of linear equations. You saw why there was a need to calculate inverses of matrices, followed by matrix multiplication to figure out the values of unknown variables. 

The exercises in this lab present some problems that can be converted into a system of linear equations. 

## Objectives
You will be able to:

- Use matrix algebra and NumPy to solve a system of linear equations given a real-life example 
- Use NumPy's linear algebra solver to solve for systems of linear equations

## Exercise 1

A coffee shop is having a sale on coffee and tea. 

On day 1, 29 bags of coffee and 41 bags of tea were sold, for a total of 490 dollars.

On day 2, they sold 23 bags of coffee and 41 bags of tea, for which customers paid a total of 448 dollars.  

How much does each bag cost?

In [4]:
# Create and solve the relevant system of equations

# import numpy
import numpy as np

# x = bags of coffee
# y = bags of tea

# A) 29x + 41y = 490
# B) 23x + 41y = 448

A = np.matrix([[29, 41], [23, 41]])
B = np.matrix([[490, 448]])

# Take the inverse of Matrix A 
A_inv = np.linalg.inv(A)

# Transpose B
B = B.T

# Calculate the dot product of inverse A and transposed B to find result
X = A_inv.dot(B)
X

matrix([[7.],
        [7.]])

In [5]:
# Describe your result

print("Each bag of coffee costs $7 and each bag of tea costs $7")

Each bag of coffee costs $7 and each bag of tea costs $7


## Exercise 2

The cost of admission to a popular music concert was 162 dollars for 12 children and 3 adults. 

The admission was 122 dollars for 8 children and 3 adults in the same music concert. 

How much was the admission for each child and adult?

In [7]:
# Create and solve the relevant system of equations

# A) 12x + 3y = 162
# B) 8x + 3y = 122

A = np.matrix([[12,3], [8,3]])
B = np.matrix([[162, 122]])

# Take inverse of A and transpose B
A_inv = np.linalg.inv(A)
B = B.T

# Calculate result
X = A_inv.dot(B)
X

matrix([[10.],
        [14.]])

In [8]:
# Describe your result
print("Each children ticket costs $10 and each adult ticket costs $14")

Each children ticket costs $10 and each adult ticket costs $14


## Exercise 3

You want to make a soup containing tomatoes, carrots, and onions.

Suppose you don't know the exact mix to put in, but you know there are 7 individual pieces of vegetables, and there are twice as many tomatoes as onions, and that the 7 pieces of vegetables cost 5.25 USD in total. 
You also know that onions cost 0.5 USD each, tomatoes cost 0.75 USD and carrots cost 1.25 USD each.

Create a system of equations to find out exactly how many of each of the vegetables are in your soup.

In [15]:
# Create and solve the relevant system of equations

# x = tomatoes, y = tomatoes, z = carrots

# A) 0.5x + 0.75y + 1.25z = 5.25   -- Total cost
# B) x + y + z = 7   -- Total number of vegetables
# C) -2x + y = 0   -- Twice as many tomatoes as onions

A = np.matrix([[0.5, 0.75, 1.25], [1, 1, 1], [-2, 1, 0]])
B = np.matrix([[5.25, 7, 0]])

# Take inverse of A and transpose B
A_inv = np.linalg.inv(A)
B = B.T

# Calculate result
X = A_inv.dot(B)
X

matrix([[2.],
        [4.],
        [1.]])

In [16]:
# Describe your result
print("The soup needs 4 tomatoes, 2 onions, and 1 carrots.")

The soup needs 4 tomatoes, 2 onions, and 1 carrots.


## Exercise 4

A landlord owns 3 properties: a 1-bedroom, a 2-bedroom, and a 3-bedroom house. 

The total rent he receives is 1240 USD. 

He needs to make some repairs, where those repairs cost 10% of the 1-bedroom house’s rent. The 2-bedroom repairs cost 20% of the 2-bedroom rental price and 30% of the 3-bedroom house's rent for its repairs.  The total repair bill for all three houses was 276 USD. 

The 3-bedroom house's rent is twice the 1-bedroom house’s rent. 

How much is the individual rent for three houses?

In [17]:
# Create and solve the relevant system of equations

# x = 1-bed rent, y = 2-bed rent, z = 3-bed rent

# A) x + y + z = 1240
# B) .1x + .2y + .3z = 276
# C) -2x + z = 0

A = np.matrix([[1, 1, 1], [.1, .2, .3], [-2, 0, 1]])
B = np.matrix([[1240, 276, 0]])

# Take inverse of A and transpose B
A_inv = np.linalg.inv(A)
B = B.T

# Calculate result
X = A_inv.dot(B)
X

matrix([[280.],
        [400.],
        [560.]])

In [18]:
# Describe your result
print("1-bed rent is $280, 2-bed rent is $400, 3-bed rent is $560")

1-bed rent is $280, 2-bed rent is $400, 3-bed rent is $560


## Summary
In this lab, you learned how to use NumPy to solve linear equations by taking inverses and matrix multiplication and also using numpy's `solve()` function. You'll now take these skills forward and see how you can define a simple regression problem using linear algebra and solve it with Numpy. 